services:
  postgres:
    container_name: vitrine-academica-postgres
    image: postgres:18
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: vitrine
      POSTGRES_PASSWORD: VACAD28
      POSTGRES_DB: vitrine_academica
    volumes:
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql